-- DDL DATA DEFINITION LANGUAGE

-- TABELA USUÁRIO

CREATE DATABASE Biblioteca;

USE Biblioteca;

CREATE TABLE livro(
idLivro INT AUTO_INCREMENT UNIQUE NOT NULL,
nome VARCHAR(100) NOT NULL,
autor VARCHAR(50) NOT NULL,
editora VARCHAR(50) NOT NULL,
PRIMARY KEY (idLivro)
);

CREATE TABLE usuario(
idUsuario int AUTO_INCREMENT UNIQUE NOT NULL,
nome VARCHAR(100) NOT NULL,
endereco VARCHAR(100) NOT NULL,
telefone VARCHAR(11) NOT NULL,
idLivro INT,
CONSTRAINT fk_usuario_livro FOREIGN KEY (idLivro) REFERENCES livro(idLivro) ON DELETE CASCADE,
PRIMARY KEY(idUsuario)
);

 